version: '3.9'

networks:
  election:

volumes:
  kong-datastore:
  keycloak-datastore:

services:
  candidatesapi:
    build: ./CandidatesAPI
    networks:
      - election
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_CandidateDatabase__DatabaseName=Candidates
      - ASPNETCORE_CandidateDatabase__ConnectionString=mongodb://mongo:27017
    deploy:
      restart_policy:
        condition: on-failure

  reportsapi:
    build: ./ReportsAPI
    networks:
      - election
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ConnectionStrings__VotesDatabase=Data Source=sqlserver; Initial Catalog=votes; User Id=sa;Password=Teste@admin123
    deploy:
      restart_policy:
        condition: on-failure

  votesapi:
    build: ./VotesAPI
    networks:
      - election
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Azure=false
      - ASPNETCORE_RabbitMQ=rabbitmq
      - ASPNETCORE_Integrations__CandidateAddress=http://candidatesapi/api/candidates/
    deploy:
      restart_policy:
        condition: on-failure

  countingworker:
    build: ./CountingWorker
    networks:
      - election
    environment:
      - DOTNET_ENVIRONMENT=Production
      - DOTNET_RabbitMQ=rabbitmq
      - DOTNET_ConnectionStrings__VotesDatabase=Data Source=sqlserver; Initial Catalog=votes; User Id=sa;Password=Teste@admin123
    deploy:
      restart_policy:
        condition: on-failure 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Teste@admin123
    ports:
      - 1433:1433
    networks:
      - election
    deploy:
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - election
    deploy:
      restart_policy:
        condition: on-failure
        
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - election
    deploy:
      restart_policy:
        condition: on-failure

  kong-db:
    image: postgres:11-alpine
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - election
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=api-gw
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    build:
      context: ./kong   
    image: kong-oidc:latest
    depends_on:
      - kong-db
    networks:
      - election
    ports:
      - 8000:8000 # Listener
      - 8001:8001 # Admin API
      - 8443:8443 # Listener  (SSL)
      - 8444:8444 # Admin API (SSL)
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=api-gw
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PLUGINS=bundled,oidc
      - KONG_LOG_LEVEL=debug
    deploy:
      restart_policy:
        condition: on-failure

  konga:
    image: pantsel/konga:0.14.9
    depends_on:
      - kong
    networks:
      - election
    ports:
      - 1337:1337 # konga
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-db
      - DB_PORT=5432
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_DATABASE=api-gw
      - NODE_ENV=development
    deploy:
      restart_policy:
        condition: on-failure

  keycloak-db:
    image: postgres:14-alpine
    volumes: 
      - keycloak-datastore:/var/lib/postgresql/data
    networks:
      - election
    ports:
      - 25432:5432
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    deploy:
      restart_policy:
        condition: on-failure

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    depends_on:
      - keycloak-db
    command: start-dev
    networks:
      - election
    ports:
      - 8180:8080
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    deploy:
      restart_policy:
        condition: on-failure