version: '3'

networks:
  election:

services:

  candidatespr:
    build: ./CandidatesPR
    ports:
      - 81:80
    networks:
      - election
    depends_on:
      - candidatesapi

  candidatesapi:
    build: ./CandidatesAPI
    networks:
      - election
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_CandidateDatabase__ConnectionString=mongodb://mongo:27017
      - ASPNETCORE_CandidateDatabase__DatabaseName=Candidates
    depends_on:
      - mongo

  votespr:
    build: ./VotesPR
    ports:
      - 82:80
    networks:
      - election
    depends_on:
      - votesapi

  votesapi:
    build: ./VotesAPI
    networks:
      - election
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ConnectionStrings__VotesDatabase=Data Source=sqlserver; Initial Catalog=votes; User Id=sa;Password=Teste@admin123
      - ASPNETCORE_Integrations__CandidateAddress=http://candidatesapi/api/candidates/
    depends_on:
      - candidatesapi
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Teste@admin123
    ports:
      - 1433:1433
    networks:
      - election

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - election