version: '3.9'

networks:
  election:

services:
  candidatesapi:
    build: ./CandidatesAPI
    networks:
      - election
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_CandidateDatabase__DatabaseName=Candidates
      - ASPNETCORE_CandidateDatabase__ConnectionString=mongodb://mongo:27017
    deploy:
      restart_policy:
        condition: on-failure

  reportsapi:
    build: ./ReportsAPI
    networks:
      - election
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ConnectionStrings__VotesDatabase=Data Source=sqlserver; Initial Catalog=votes; User Id=sa;Password=Teste@admin123
    deploy:
      restart_policy:
        condition: on-failure

  votesapi:
    build: ./VotesAPI
    networks:
      - election
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Azure=false
      - ASPNETCORE_RabbitMQ=rabbitmq
      - ASPNETCORE_Integrations__CandidateAddress=http://candidatesapi/api/candidates/
    deploy:
      restart_policy:
        condition: on-failure

  countingworker:
    build: ./CountingWorker
    networks:
      - election
    environment:
      - DOTNET_ENVIRONMENT=Production
      - DOTNET_RabbitMQ=rabbitmq
      - DOTNET_ConnectionStrings__VotesDatabase=Data Source=sqlserver; Initial Catalog=votes; User Id=sa;Password=Teste@admin123
    deploy:
      restart_policy:
        condition: on-failure 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Teste@admin123
    ports:
      - 1433:1433
    networks:
      - election
    deploy:
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - election
    deploy:
      restart_policy:
        condition: on-failure
        
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - election
    deploy:
      restart_policy:
        condition: on-failure